KAN-114-auto-tf-resource
ib-agent/github-workflow pull request #8
Opened 2024-09-10 14:12 UTC by canle144

- Update to add new env from configurating repo
- Add new workflow 
- https://cabernet-ai.atlassian.net/browse/KAN-114
- Testing: https://github.com/ib-agent/can1-service/actions/runs/10793828204

2024-09-10 14:14 UTC, canle144 commented
PR relates to https://github.com/ib-agent/cookiecutter-python-service/pull/6

2024-09-12 15:12 UTC, brook-cabernet requested changes

2024-09-16 10:26 UTC, canle144 commented on .github/workflows/configure-repo.yaml
> +          gh variable set PYTHON_TF_INIT_ROLE_TO_ASSUME --repo ${{ github.repository }} --env=development --body="arn:aws:iam::${{ github.event.inputs.aws_account_id_dev }}:role/Python-TF-Init-GitHub
removed

2024-09-17 02:23 UTC, brook-cabernet commented on .github/workflows/terraform-python-init.yaml
> +      - name: Create policies & attatch to GitHubActionsRole
nice

2024-09-17 02:24 UTC, brook-cabernet commented on .github/workflows/terraform-python.yaml
> -        working-directory: ./tf/main
this will break existing projects, so we need to backfill existing projects with a version tag?

2024-09-18 02:46 UTC, brook-cabernet approved these changes

2024-09-18 02:48 UTC, merged

2024-09-18 02:48 UTC, cabernet-ib-agent-workflow commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on [GitHub release](https://github.com/ib-agent/github-workflow/releases/tag/2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: